# Generated by Django 4.0 on 2022-07-01 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_apparels_and_accessories_ads_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Sub'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='Category',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
    ]
