# Generated by Django 4.0.1 on 2022-07-27 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_alter_category_options_sub_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=100)),
                ('about_yourself', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Apparels_and_Accessories_Ads',
        ),
        migrations.DeleteModel(
            name='Furniture_Ads',
        ),
        migrations.DeleteModel(
            name='Job_Ads',
        ),
        migrations.DeleteModel(
            name='Real_Estate_Ads',
        ),
        migrations.DeleteModel(
            name='Stationery_items_Ads',
        ),
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mobile_and_accessories_ads',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vehicle_ads',
            name='title',
        ),
        migrations.RemoveField(
            model_name='vehicle_ads',
            name='year',
        ),
        migrations.AddField(
            model_name='electronics_tvs_and_more_ads',
            name='additional_details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='electronics_tvs_and_more_ads',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_and_accessories_ads',
            name='additional_details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mobile_and_accessories_ads',
            name='battery_health',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='mobile_and_accessories_ads',
            name='brand',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='mobile_and_accessories_ads',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mobile_and_accessories_ads',
            name='model_name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_ads',
            name='additional_details',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_ads',
            name='company_name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_ads',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle_ads',
            name='vehicle_name',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='electronics_tvs_and_more_ads',
            name='Description',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='electronics_tvs_and_more_ads',
            name='title',
            field=models.CharField(blank=True, max_length=122, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_ads',
            name='model',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sub_Category',
        ),
        migrations.AddField(
            model_name='useritem',
            name='electronics_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.electronics_tvs_and_more_ads'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='mobiles_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mobile_and_accessories_ads'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='vehicels_ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicle_ads'),
        ),
        migrations.AddField(
            model_name='electronics_tvs_and_more_ads',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
        migrations.AddField(
            model_name='mobile_and_accessories_ads',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
        migrations.AddField(
            model_name='vehicle_ads',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.customer'),
        ),
    ]
