# Generated by Django 4.0.1 on 2022-07-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_useritem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserItem',
        ),
    ]
