# Generated by Django 4.0.1 on 2022-07-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_alter_customer_location_alter_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('electronics_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.electronics_tvs_and_more_ads')),
                ('mobiles_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.mobile_and_accessories_ads')),
                ('vehicels_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.vehicle_ads')),
            ],
        ),
    ]
