# Generated by Django 4.0.1 on 2022-07-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_useritem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='about_yourself',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
